### ISSUE TITLE
kaizenplatform/fluent-plugin-bigquery

### ISSUE THREAD

**Issue by ryopeko** [fluent-plugins-nursery/contact#10]
Please set the name of your Fluent plugin as the issue title.

## The repository URL of your Fluent plugin
https://github.com/kaizenplatform/fluent-plugin-bigquery

## Do you want us to add you to this GitHub organization?

Yes

**Comment by cosmo0920** [comment]
I've invited you to this organization.
Could you transfer ownership to this organization?
And then could you add me to owner of gem?

```
gem owner GEM -a cosmo0920.oucc@gmail.com
```

**Comment by joker1007** [comment]
Hi :hand: 
I'm main maintainer of fluent-plugin-bigquery but I'm not kaizenplatform member.
The main purpose is that it solves mismatch between maintainers and current organization. 
And I will continue to maintain it.
Because of it, I want you to add me to this Github org and administrators the repository.

**Comment by cosmo0920** [comment]
Yeah. I've also invited @joker1007 as a member of original authors team!

**Comment by okkez** [comment]
@ryopeko @joker1007 Any progress?

**Comment by ryopeko** [comment]
@okkez 
sorry. I just transferred to fluent-plugins-nursery.

**Comment by okkez** [comment]
Thanks!
I've confirmed.
